version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: shan20
      MYSQL_DATABASE: antony
    ports:
      - "4000:3306" # MySQL typically runs on port 3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root20:shan20@172.24.186.65:3306/antony # Use the service name 'db'
    volumes:
      - ./D:/docker/THH_BackEnd/model-best:/app/model-best # Adjust this path to your host model directory

volumes:
  db_data:


